### ISSUE TITLE
Workflow Rust / build failure

### ISSUE THREAD

**Issue by rodrigo-romano** [rconan/dos-actors#22]
The build job fails. Is seems to be something related to the `serve` crate dependency.
![build_job_failure_msg](https://github.com/rconan/dos-actors/assets/10143022/28b8e738-9273-476b-a32d-597ac7159c80)

**Comment by rconan** [comment]
The `serde` dependency is optional for the `gmt_dos-clients` crate,  replacing `#[serde(skip)` with `#[cfg_attr(feature = "serde", serde(skip))]` fix the issue
